### ISSUE TITLE
older  ds3 subversions 

### ISSUE THREAD

**Issue by GaDemICE** [The-Grand-Archives/Dark-Souls-III-CT-TGA#27]
lets just say updating the game isnt an option for me currently so i'm stuck with 1.15
does anyone by any chance have the version of this that was for  1.15? 
im just kinda shooting in the dark but i hope someone has the 1.15 version in some corner...

**Comment by Limezero** [comment]
The repository itself still has every previous version, just download one of those. Release [v2.3.2](https://github.com/The-Grand-Archives/Dark-Souls-III-CT-TGA/releases/tag/v2.3.2) works fine for me on 1.15.0.

**Comment by GaDemICE** [comment]
Thanks a lot, I had tried to find previous versions but I guess i was not comfortable enough with the platform to find it.
