### ISSUE TITLE
Add Targeted Entity Info

### ISSUE THREAD

**Issue by Biggestmeme** [The-Grand-Archives/Dark-Souls-III-CT-TGA#35]
in this table there are is no possibility to get info for the targeted entity or any entity at all.

**Comment by inuNorii** [comment]
Seems I forgot about those old helpers.
For now you can use `Scripts -> Functions -> Npc Spawn and Control -> Npc Control`.

**Comment by Biggestmeme** [comment]
> Seems I forgot about those old helpers.

I used them for some bots, I tried the old table from Igromanru and the script that injects some asm for the targeted entity info still works.
