### ISSUE TITLE
Gestures don't work? 

### ISSUE THREAD

**Issue by lognts** [The-Grand-Archives/Dark-Souls-III-CT-TGA#36]
Anytime I have tried adding a gesture in ds3 it won't work.

**Comment by inuNorii** [comment]
How were you trying to add them?

**Comment by lognts** [comment]
Through Item Gib. I added them through Build Creation < Add all Gestures instead and that worked. For some reason Londor pale shade did not give me his gesture when I summoned him at pontiff sulyvahn. So, I did add all gestures instead and I didn't get the achievement. I assume I have to be online to get the achievement but not sure.

**Comment by inuNorii** [comment]
The items are useless, they only exist for the fake item get popup when you normally acquire a gesture.
The achievement is likely tied to having triggered the relevant events for each gesture, but you can just use TrophyUnlock from the table or Steam Achievement Manager to unlock that.
