### ISSUE TITLE
Unlimited items?

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [The-Grand-Archives/Dark-Souls-III-CT-TGA#39]
Is there a script to make it the item quantity stay the same when I use it?

**Comment by inuNorii** [comment]
There is a character flag called NoGoodsConsume.
This is not an issue.

**Comment by inuNorii** [comment]
NoGoodsConsume works correctly.
I assume you're trying to tick the box to 'toggle' it, but that won't work as flags aren't scripts.
Ticking the box will only freeze the value, which you need to set to 1 or 0.

Also, Github issues are generally not for support questions.
We have a discord for that.
