### ISSUE TITLE
Version check fail

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [The-Grand-Archives/Dark-Souls-III-CT-TGA#41]
Whenever I open the 1st checkbox, it takes 1 minute due to the version check failing. Everything in the script works fine though. It's just annoying to wait 1 minute every time.

**Comment by inuNorii** [comment]
It's an issue on your end. Make sure you don't have a firewall or anti-virus software blocking requests to Github.

If you don't know enough about the system you're running you can disable the update check in Table Config, but don't ask for support if you end up running outdated versions of the cheat table.

**Comment by asdsadsaasd12312132** [comment]
I'm using the latest cheat table. Is there anyway to disable the update check? It doesn't work for me.

**Comment by inuNorii** [comment]
Read my previous answer again.
