### ISSUE TITLE
TP to self for backstab.

### ISSUE THREAD

**Issue by Gossan111** [The-Grand-Archives/Dark-Souls-III-CT-TGA#46]
TP to self for backstab.
<<Error in line 125 (InstaStuff3+38:): This address specifier is not valid>>

**Comment by boblord14** [comment]
nobody's bothered to fix that, and odds are it wont be fixed due to being an online cheat

**Comment by Gossan111** [comment]
> 没有人费心去解决这个问题，而且很有可能由于是在线作弊而无法修复

ummmmmm

**Comment by inuNorii** [comment]
No.

**Comment by reyesc02** [comment]
😎
