### ISSUE TITLE
Sister Friede not reviving

### ISSUE THREAD

**Issue by humam2104** [The-Grand-Archives/Dark-Souls-III-CT-TGA#50]
I tried many times to revive sister friede. It just doesn't work as the door leading to the fight is closed. And bypassing it makes the boss idle and doesn't start the fight. Could you please fix that?

**Comment by inuNorii** [comment]
There's nothing to fix.
You need to set all relevant events to the correct states.

**Comment by humam2104** [comment]
Can you explain that? I changed both flags in the cheat table but it didn't work.
What events do I need to change exactly?
